<a href="https://colab.research.google.com/github/HusanJalilov/AI_Jpyuter_/blob/main/fayllar_bilan_ishlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr=np.arange(9)


In [2]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
np.save('data',arr)   # faylga saqlash uchun ishlatiladigan metod


In [10]:
arr2=np.load('data.npy')  # saqlangan faylni o'qish uchun ishlatiladigan metod

In [11]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
arr3=np.arange(19)


In [15]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [16]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
arrays=np.savez('arrays', a=arr2,b=arr3)   # ko'proq massivlarni o'z ichiga olgan metod

In [19]:
s=np.load('arrays.npz')   # faylni chqairish

In [21]:
s['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
s['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [28]:
x=np.savez_compressed('save_compressor',a=arr2,b=arr3) # zichlangan arraylar jamlanmasi