<a href="https://colab.research.google.com/github/HusanJalilov/AI_Jpyuter_/blob/main/mantiqiy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr=np.random.randn(5,4)


In [2]:
arr

array([[ 0.2045939 , -0.47962897, -1.1253354 ,  0.66412698],
       [-0.82113113,  0.55811484, -2.9171583 , -1.41101156],
       [-1.14693552, -0.91680454, -1.50200344, -0.02960823],
       [ 0.50282793,  0.47249982, -0.26261411,  0.12024192],
       [ 0.98368047,  1.02410151, -1.51590198,  0.45758891]])

In [3]:
arr.sum()

-7.140356893725236

In [5]:
arr=np.sum(arr)

In [6]:
arr

-7.140356893725236

In [10]:
data=np.arange(6)
data=np.mean(data)

In [11]:
data

2.5

In [12]:
data


2.5

In [13]:
sum=np.arange(5)

In [14]:
sum

array([0, 1, 2, 3, 4])

In [15]:
sum.cumsum()

array([ 0,  1,  3,  6, 10])