<a href="https://colab.research.google.com/github/HusanJalilov/AI_Jpyuter_/blob/main/Matematik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a=2


In [2]:
a

2

In [3]:
import numpy as np

In [14]:
import numpy as np
a=np.arange(6).reshape(2,3)
b=np.arange(6,12).reshape(2,3)
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [15]:
a*b

array([[ 0,  7, 16],
       [27, 40, 55]])

In [16]:
a/b

array([[0.        , 0.14285714, 0.25      ],
       [0.33333333, 0.4       , 0.45454545]])

In [17]:
b-a

array([[6, 6, 6],
       [6, 6, 6]])

In [18]:
b**2  # b massiv elementlarini kvadratga ko'taradi 

array([[ 36,  49,  64],
       [ 81, 100, 121]])

In [19]:
a**3  # a massiv elementlarini kubga ko'taradi

array([[  0,   1,   8],
       [ 27,  64, 125]])