<a href="https://colab.research.google.com/github/HusanJalilov/AI_Jpyuter_/blob/main/numpy_arry.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
data1=[2,3,8,9.3]  # list yaratish
arr1=np.array(data1)  #  array1 yaratish

In [3]:
arr1

array([2. , 3. , 8. , 9.3])

In [4]:
data1

[2, 3, 8, 9.3]

In [5]:
data2=(2,8,3,3.4)  #  Tuple yaratildi
arr2=np.array(data2)  #  Array2 yaratildi


In [6]:
arr2

array([2. , 8. , 3. , 3.4])

In [7]:
data2

(2, 8, 3, 3.4)

In [8]:
arr2.ndim  #  Array2 ning massiv o'lchami 

1

In [9]:
arr1.ndim  # Array1 ning massiv o'lchami

1

Endi ikki o'lchovli massiv yaratamiz:  

In [10]:
data3=[[2,4,5],[7,8,99]]  # 2 o'chovli list
arr3=np.array(data3)  # 2 o'chovli MASSIV

In [12]:
arr3.ndim #  arr3 ning massiv o'lchami

2

- Shape va size metodlari


In [22]:
arr3.shape  #  qator va ustunlar sonini kursatadi


(2, 3)

In [23]:
arr3.size  #  arr3 ning elementlari soni

6

**  N o'lchamli massivlar yaratishning boshqa usullari**

-zeros  va ones funksiyalari yordamida massivlar yaratish

In [24]:
arr4=np.zeros(shape=(3,4))  # barcha elementlari 0 dan iborat massiv
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
arr5=np.ones(shape=(2,6)) # barcha elementlari 1 dan ibora massiv
arr5

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [29]:
arr6=np.arange(4,18,3) # 4 dan 18 gacha saonlarni 3 qadam bilan massivga joylab beradi
arr6

array([ 4,  7, 10, 13, 16])