<a href="https://colab.research.google.com/github/HusanJalilov/AI_Jpyuter_/blob/main/pandas/Data_frame_elementlarni_Tanlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np


In [8]:
uz={2018:31.3,2019:32.3,2020:33.2,2021:35}
rus={2018:102.3,2019:103.3,2020:104.2,2021:105}
itl={2018:51.3,2019:52.3,2020:54.2,2021:56}
kg={2018:72.3,2019:74,2020:76,2021:80}
ger={2018:29.3,2019:22.3,2020:34.2,2021:67}

In [9]:
df=pd.DataFrame(
    {
        'Uzbekistan':uz,
     'Russia':rus,
     'Italiya':itl,
     'Kazakistan':kg,
     'Germaniya':ger
    }
)

In [10]:
df[['Uzbekistan']]  # bu DataFrame ko'rinishda chaqairib olish

Uzbekistan
2018        31.3
2019        32.3
2020        33.2
2021        35.0

In [11]:
df['Uzbekistan']  # bu esa Series ko'riinishda chaqairib olish

2018    31.3
2019    32.3
2020    33.2
2021    35.0
Name: Uzbekistan, dtype: float64

In [12]:
df['Uzbekistan'].to_numpy() # bu Numpy ko'rinishiga o'tkazish

array([31.3, 32.3, 33.2, 35. ])

In [13]:
df[['Uzbekistan','Italiya']]

Uzbekistan  Italiya
2018        31.3     51.3
2019        32.3     52.3
2020        33.2     54.2
2021        35.0     56.0

In [14]:
df>10


Uzbekistan  Russia  Italiya  Kazakistan  Germaniya
2018        True    True     True        True       True
2019        True    True     True        True       True
2020        True    True     True        True       True
2021        True    True     True        True       True

In [15]:
df


Uzbekistan  Russia  Italiya  Kazakistan  Germaniya
2018        31.3   102.3     51.3        72.3       29.3
2019        32.3   103.3     52.3        74.0       22.3
2020        33.2   104.2     54.2        76.0       34.2
2021        35.0   105.0     56.0        80.0       67.0

In [16]:
df>60  # bu yerda Qiymatlari 60 dan katta lar true aksiznch afalse qiymat chiqaradi


Uzbekistan  Russia  Italiya  Kazakistan  Germaniya
2018       False    True    False        True      False
2019       False    True    False        True      False
2020       False    True    False        True      False
2021       False    True    False        True       True

In [17]:
df.index

Int64Index([2018, 2019, 2020, 2021], dtype='int64')

In [18]:
s=df.index.to_numpy()
s

array([2018, 2019, 2020, 2021])

In [19]:
s=np.sort(s)
s

array([2018, 2019, 2020, 2021])

In [20]:
df[['Italiya']]

Italiya
2018     51.3
2019     52.3
2020     54.2
2021     56.0

In [21]:
df[['Italiya']][df['Italiya']>52]  # ikkkitalik shart bajarish usuli

Italiya
2019     52.3
2020     54.2
2021     56.0

In [22]:
dfuz=df[['Uzbekistan']]
dfuz

Uzbekistan
2018        31.3
2019        32.3
2020        33.2
2021        35.0

In [24]:
dfuz[dfuz['Uzbekistan']>32]

Uzbekistan
2019        32.3
2020        33.2
2021        35.0

In [25]:
df

Uzbekistan  Russia  Italiya  Kazakistan  Germaniya
2018        31.3   102.3     51.3        72.3       29.3
2019        32.3   103.3     52.3        74.0       22.3
2020        33.2   104.2     54.2        76.0       34.2
2021        35.0   105.0     56.0        80.0       67.0

In [27]:
df2=df.transpose(copy=True)

In [28]:
df2

2018   2019   2020   2021
Uzbekistan   31.3   32.3   33.2   35.0
Russia      102.3  103.3  104.2  105.0
Italiya      51.3   52.3   54.2   56.0
Kazakistan   72.3   74.0   76.0   80.0
Germaniya    29.3   22.3   34.2   67.0

In [29]:
df2[df2[2019]>50]  # bu yerda ham ko'rib turganinggizdek filtr va ozgartirish

2018   2019   2020   2021
Russia      102.3  103.3  104.2  105.0
Italiya      51.3   52.3   54.2   56.0
Kazakistan   72.3   74.0   76.0   80.0